#  Copyright 2022 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# flake8: noqa


# This file is automatically generated. Please do not modify it directly.
# Find the relevant recipe file in the samples/recipes or samples/ingredients
# directory and apply your changes there.


# [START compute_instances_create]
from __future__ import annotations

import re
import sys
from typing import Any
import warnings

from google.api_core.extended_operation import ExtendedOperation
from google.cloud import compute_v1

from google.api_core.exceptions import NotFound

def ensure_firewall_rule(
    project_id: str,
    firewall_rule_name: str = "allow-5000",
    network_link: str = "global/networks/default",
) -> None:
    """
    Checks if a firewall rule exists. If not, creates it allowing TCP port 5000
    from 0.0.0.0/0 to VMs tagged with the rule name.
    """
    firewall_client = compute_v1.FirewallsClient()

    # 1. Check if the firewall rule already exists
    try:
        firewall_client.get(project=project_id, firewall=firewall_rule_name)
        print(f"Firewall rule '{firewall_rule_name}' already exists. Skipping creation.")
        return
    except NotFound:
        print(f"Firewall rule '{firewall_rule_name}' not found. Creating it...")

    # 2. Define the firewall rule resource
    firewall_rule = compute_v1.Firewall()
    firewall_rule.name = firewall_rule_name
    firewall_rule.direction = "INGRESS"
    firewall_rule.network = network_link
    firewall_rule.source_ranges = ["0.0.0.0/0"]
    firewall_rule.target_tags = ["allow-5000"]

    # Allow TCP on port 5000
    allowed_ports = compute_v1.Allowed()
    allowed_ports.I_p_protocol = "tcp"
    allowed_ports.ports = ["5000"]
    firewall_rule.allowed = [allowed_ports]

    # 3. Insert the firewall rule and wait for operation to complete
    operation = firewall_client.insert(
        project=project_id, firewall_resource=firewall_rule
    )
    wait_for_extended_operation(operation, f"creating firewall rule {firewall_rule_name}")
    print(f"Firewall rule '{firewall_rule_name}' successfully created.")

def get_image_from_family(project: str, family: str) -> compute_v1.Image:
    image_client = compute_v1.ImagesClient()
    # List of public operating system (OS) images: https://cloud.google.com/compute/docs/images/os-details
    newest_image = image_client.get_from_family(project=project, family=family)
    return newest_image


def disk_from_image(
    disk_type: str,
    disk_size_gb: int,
    boot: bool,
    source_image: str,
    auto_delete: bool = True,
) -> compute_v1.AttachedDisk:

    boot_disk = compute_v1.AttachedDisk()
    initialize_params = compute_v1.AttachedDiskInitializeParams()
    initialize_params.source_image = source_image
    initialize_params.disk_size_gb = disk_size_gb
    initialize_params.disk_type = disk_type
    boot_disk.initialize_params = initialize_params
    # Remember to set auto_delete to True if you want the disk to be deleted when you delete
    # your VM instance.
    boot_disk.auto_delete = auto_delete
    boot_disk.boot = boot
    return boot_disk


def wait_for_extended_operation(
    operation: ExtendedOperation, verbose_name: str = "operation", timeout: int = 300
) -> Any:
    result = operation.result(timeout=timeout)

    if operation.error_code:
        print(
            f"Error during {verbose_name}: [Code: {operation.error_code}]: {operation.error_message}",
            file=sys.stderr,
            flush=True,
        )
        print(f"Operation ID: {operation.name}", file=sys.stderr, flush=True)
        raise operation.exception() or RuntimeError(operation.error_message)

    if operation.warnings:
        print(f"Warnings during {verbose_name}:\n", file=sys.stderr, flush=True)
        for warning in operation.warnings:
            print(f" - {warning.code}: {warning.message}", file=sys.stderr, flush=True)

    return result
def add_network_tag(project_id, zone, instance_name, tag):
    client = compute_v1.InstancesClient()

    instance = client.get(
        project=project_id,
        zone=zone,
        instance=instance_name,
    )

    tags = compute_v1.Tags()

    # Keep any existing tags
    tags.items = list(instance.tags.items) if instance.tags else []

    # Add the new tag
    if tag not in tags.items:
        tags.items.append(tag)

    # IMPORTANT: setTags requires the current fingerprint
    if instance.tags:
        tags.fingerprint = instance.tags.fingerprint

    request = compute_v1.SetTagsInstanceRequest(
        project=project_id,
        zone=zone,
        instance=instance_name,
        tags_resource=tags,
    )

    operation = client.set_tags(request=request)

    wait_for_extended_operation(
        operation,
        "setting network tag",
    )

    print(f"Network tag '{tag}' added to {instance_name}.")

def create_instance(
    project_id: str,
    zone: str,
    instance_name: str,
    disks: list[compute_v1.AttachedDisk],
    machine_type: str = "f1-micro", #change this to lower resources 
    network_link: str = "global/networks/default",
    subnetwork_link: str = None,
    internal_ip: str = None,
    external_access: bool = False,
    external_ipv4: str = None,
    accelerators: list[compute_v1.AcceleratorConfig] = None,
    preemptible: bool = False,
    spot: bool = False,
    instance_termination_action: str = "STOP",
    custom_hostname: str = None,
    delete_protection: bool = False,
) -> compute_v1.Instance:


    with open("startup.sh", "r") as f:
        startup_script = f.read()

    metadata = compute_v1.Metadata()
    metadata.items = [
        compute_v1.Items(
            key="startup-script",
            value=startup_script,
        )
    ]
    instance = compute_v1.Instance()
    instance.metadata = metadata

    instance_client = compute_v1.InstancesClient()

    # Use the network interface provided in the network_link argument.
    network_interface = compute_v1.NetworkInterface()
    network_interface.network = network_link
    if subnetwork_link:
        network_interface.subnetwork = subnetwork_link

    if internal_ip:
        network_interface.network_i_p = internal_ip

    if external_access:
        access = compute_v1.AccessConfig()
        access.type_ = "ONE_TO_ONE_NAT"
        access.name = "External NAT"
        access.network_tier = "PREMIUM"

        if external_ipv4:
            access.nat_i_p = external_ipv4

        network_interface.access_configs = [access]

    instance.network_interfaces = [network_interface]
    instance.name = instance_name
    instance.disks = disks
    if re.match(r"^zones/[a-z\d\-]+/machineTypes/[a-z\d\-]+$", machine_type):
        instance.machine_type = machine_type
    else:
        instance.machine_type = f"zones/{zone}/machineTypes/{machine_type}"

    instance.scheduling = compute_v1.Scheduling()
    if accelerators:
        instance.guest_accelerators = accelerators
        instance.scheduling.on_host_maintenance = (
            compute_v1.Scheduling.OnHostMaintenance.TERMINATE.name
        )

    if preemptible:
        # Set the preemptible setting
        warnings.warn(
            "Preemptible VMs are being replaced by Spot VMs.", DeprecationWarning
        )
        instance.scheduling = compute_v1.Scheduling()
        instance.scheduling.preemptible = True

    if spot:
        # Set the Spot VM setting
        instance.scheduling.provisioning_model = (
            compute_v1.Scheduling.ProvisioningModel.SPOT.name
        )
        instance.scheduling.instance_termination_action = instance_termination_action

    if custom_hostname is not None:
        # Set the custom hostname for the instance
        instance.hostname = custom_hostname

    if delete_protection:
        # Set the delete protection bit
        instance.deletion_protection = True

    # Prepare the request to insert an instance.
    request = compute_v1.InsertInstanceRequest()
    request.zone = zone
    request.project = project_id
    request.instance_resource = instance

    # Wait for the create operation to complete.
    print(f"Creating the {instance_name} instance in {zone}...")

    operation = instance_client.insert(request=request)

    wait_for_extended_operation(operation, "instance creation")

    print(f"Instance {instance_name} created.")
    return instance_client.get(project=project_id, zone=zone, instance=instance_name)


# [END compute_instances_create]

if __name__ == "__main__":
    import uuid
    import google.auth
    import google.auth.exceptions

    try:
        default_project_id = google.auth.default()[1]
    except google.auth.exceptions.DefaultCredentialsError:
        print(
            "Please use `gcloud auth application-default login` "
            "or set GOOGLE_APPLICATION_CREDENTIALS to use this script."
        )
    else:
        instance_name = "quickstart-" + uuid.uuid4().hex[:10]
        instance_zone = "us-west2-a"

        # Create the firewall rule
        ensure_firewall_rule(default_project_id)

        # Get the latest Ubuntu 22.04 image
        newest_ubuntu = get_image_from_family(
            project="ubuntu-os-cloud",
            family="ubuntu-2204-lts",
        )

        # Create boot disk
        disk_type = f"zones/{instance_zone}/diskTypes/pd-standard"

        disks = [
            disk_from_image(
                disk_type,
                10,
                boot=True,
                source_image=newest_ubuntu.self_link,
                auto_delete=True,
            )
        ]

        # Create VM with external IP and startup script
        created_instance = create_instance(
            default_project_id,
            instance_zone,
            instance_name,
            disks,
            machine_type="f1-micro",
            external_access=True,
        )

        # Apply allow-5000 network tag using setTags API
        add_network_tag(
            default_project_id,
            instance_zone,
            instance_name,
            "allow-5000",
        )

        # Get the VM again so we have the current instance information
        instance_client = compute_v1.InstancesClient()

        created_instance = instance_client.get(
            project=default_project_id,
            zone=instance_zone,
            instance=instance_name,
        )

        # Retrieve external IP
        external_ip = (
            created_instance.network_interfaces[0]
            .access_configs[0]
            .nat_i_p
        )

        print("\nThe Flask application is available at:")
        print(f"http://{external_ip}:5000")
